In [1]:
import numpy as np 
import pandas as pd 
import re
import nltk 
import matplotlib.pyplot as plt
%matplotlib inline

### Load the csv file available in the working or specified directory

In [2]:
#import os
#os.chdir('C:\\GL Class\DSBA - Python\Machine Learning\Week 4')
tweets = pd.read_excel("Tweet_NFT.xlsx")

In [3]:
tweets.head()

id                                         tweet_text  \
0  1212762  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1  1212763  Need Sick Character art❓#art #artist #Artist...   
2  1212765  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3  1212766  @CryptoBatzNFT @DarekBTW The first project in ...   
4  1212767  @sashadysonn The first project in crypto with ...   

           tweet_created_at  tweet_intent  
0  2022-08-06T16:56:36.000Z     Community  
1  2022-08-06T16:56:36.000Z      Giveaway  
2  2022-08-06T16:56:35.000Z  Appreciation  
3  2022-08-06T16:56:35.000Z     Community  
4  2022-08-06T16:56:34.000Z     Community

In [4]:
tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127453 entries, 0 to 127452
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   id                127453 non-null  int64 
 1   tweet_text        127453 non-null  object
 2   tweet_created_at  127453 non-null  object
 3   tweet_intent      96364 non-null   object
dtypes: int64(1), object(3)
memory usage: 3.9+ MB


In [5]:
## Let's get the count of Airline
print(tweets['tweet_intent'].nunique())
print(tweets['tweet_intent'].value_counts().sort_values())

9
Launching Soon      133
Interested          276
pinksale            477
Done               3049
Presale            5107
Whitelist          8320
Appreciation      16451
Giveaway          21041
Community         41510
Name: tweet_intent, dtype: int64


In [6]:
tweets.shape 

(127453, 4)

In [7]:
### Check for null values

In [8]:
((tweets.isnull() | tweets.isna()).sum() * 100 / tweets.index.size).round(2)

id                   0.00
tweet_text           0.00
tweet_created_at     0.00
tweet_intent        24.39
dtype: float64

### Let's get a word count without writing a lambda function

In [9]:
tweets['totalwords'] = [len(x.split()) for x in tweets['tweet_text'].tolist()]
tweets[['tweet_text','totalwords']].head()

tweet_text  totalwords
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...          48
1  Need Sick Character art❓#art #artist #Artist...          25
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...          12
3  @CryptoBatzNFT @DarekBTW The first project in ...          35
4  @sashadysonn The first project in crypto with ...          34

### Number of Characters- including spaces

In [10]:
tweets['char_count'] = tweets['tweet_text'].str.len() ## this also includes spaces
tweets[['tweet_text','char_count']].head()


tweet_text  char_count
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...         471
1  Need Sick Character art❓#art #artist #Artist...         294
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...          95
3  @CryptoBatzNFT @DarekBTW The first project in ...         284
4  @sashadysonn The first project in crypto with ...         272

### Average Word Length:

In [11]:
def avg_word(sentence):
    words = sentence.split()
    return (sum(len(word) for word in words)/len(words))

tweets['avg_word'] = tweets['tweet_text'].apply(lambda x: avg_word(x))
tweets[['tweet_text','avg_word']].head()

tweet_text   avg_word
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   8.791667
1  Need Sick Character art❓#art #artist #Artist...  10.800000
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   7.000000
3  @CryptoBatzNFT @DarekBTW The first project in ...   6.885714
4  @sashadysonn The first project in crypto with ...   6.764706

In [12]:
!pip install nltk

In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91982\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Number of stop Words:

In [14]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

tweets['stopwords'] = tweets['tweet_text'].apply(lambda x: len([x for x in x.split() if x in stop]))
tweets[['tweet_text','stopwords']].head()

tweet_text  stopwords
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...         11
1  Need Sick Character art❓#art #artist #Artist...          0
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...          2
3  @CryptoBatzNFT @DarekBTW The first project in ...          8
4  @sashadysonn The first project in crypto with ...          8

### Number of special character:

In [15]:
tweets['hastags'] = tweets['tweet_text'].apply(lambda x: len([x for x in x.split() if x.startswith('@')]))
tweets[['tweet_text','hastags']].head()

tweet_text  hastags
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...       15
1  Need Sick Character art❓#art #artist #Artist...        5
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...        5
3  @CryptoBatzNFT @DarekBTW The first project in ...        2
4  @sashadysonn The first project in crypto with ...        1

### Number of numerics:

In [16]:
tweets['numerics'] = tweets['tweet_text'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
tweets[['tweet_text','numerics']].head()

tweet_text  numerics
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...         0
1  Need Sick Character art❓#art #artist #Artist...         0
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...         0
3  @CryptoBatzNFT @DarekBTW The first project in ...         0
4  @sashadysonn The first project in crypto with ...         0

### Number of Uppercase Words:

In [17]:
tweets['upper'] = tweets['tweet_text'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
tweets[['tweet_text','upper']].head()

tweet_text  upper
0  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...      2
1  Need Sick Character art❓#art #artist #Artist...      1
2  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...      0
3  @CryptoBatzNFT @DarekBTW The first project in ...      3
4  @sashadysonn The first project in crypto with ...      3

In [18]:

labels = tweets.iloc[:, 1].values

In [19]:
labels

array(["@crypto_brody @eCoLoGy1990 @MoonrunnersNFT @ItsukiNFT @thelittlesnft @SpaceRiders_NFT @WDoopsies @WomenandWeapons @WoWPixiesNFT @BokiNFT @quirkiesnft @bitcoin_bowie @Kal_El_Krypto_ @sophiegreen86 ðŸ\x90¶ A new cryptocurrency was born by fans of the Chihuahua meme community. It's just simply pets love and keep 1% from each transaction which will be automatically distributed. \n‼ï¸\x8fCA: 0x2fd6c9B869Dea106730269E13113361b684f843a\n @Chihuahua_bsc\nTG: https://t.co/wqSzCivfaM",
       'Need Sick Character artâ\x9d“#art #artist #Artists #animation #illustrators #illustrations #illustrationart #NFT #NFTGiveaways #3Danimation #3dart #conceptart #Concept #illustrators #SolanaNFTs #ArtistOnTwitter @ScrimFinder @BlazedRTs @SGH_RTs @smallstreamhype @ShoutGamers https://t.co/Nf3Egckt78',
       '@The_Hulk_NFT @INagotchiNFT @Tesla @killabearsnft @elonmusk Great choice on a Tesla! Good luck!',
       ...,
       '@leeneedham81 @KibaInuWorld @HODL_OFFICIAL @KoaCombat @Cliff_Classic 100% o

In [20]:
for feature in tweets.columns:
    if tweets[feature].dtype=='object':
        tweets[feature]=pd.Categorical(tweets[feature]).codes

### Model Building

In [21]:
X = tweets.drop(['tweet_intent'] , axis=1)
y = tweets.pop('tweet_intent')

In [22]:
y

0         1
1         3
2         0
3         1
4         1
         ..
127448   -1
127449   -1
127450   -1
127451   -1
127452   -1
Name: tweet_intent, Length: 127453, dtype: int8

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X, y, test_size = 0.30, random_state = 0)

In [24]:
from sklearn.ensemble import RandomForestClassifier

RF_model = RandomForestClassifier(n_estimators=200, random_state=0)
RF_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=0)

In [25]:
## Performance Matrix on train data set
from sklearn import metrics
y_train_predict = RF_model.predict(X_train)
model_score =RF_model.score(X_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

1.0
[[21765     0     0     0     0     0     0     0     0     0]
 [    0 11415     0     0     0     0     0     0     0     0]
 [    0     0 29113     0     0     0     0     0     0     0]
 [    0     0     0  2212     0     0     0     0     0     0]
 [    0     0     0     0 14708     0     0     0     0     0]
 [    0     0     0     0     0   186     0     0     0     0]
 [    0     0     0     0     0     0    88     0     0     0]
 [    0     0     0     0     0     0     0  3515     0     0]
 [    0     0     0     0     0     0     0     0  5877     0]
 [    0     0     0     0     0     0     0     0     0   338]]
              precision    recall  f1-score   support

          -1       1.00      1.00      1.00     21765
           0       1.00      1.00      1.00     11415
           1       1.00      1.00      1.00     29113
           2       1.00      1.00      1.00      2212
           3       1.00      1.00      1.00     14708
           4       1.00      1.00      1

In [26]:
## Performance Matrix on test data set
y_test_predict = RF_model.predict(X_test)
model_score = RF_model.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_test_predict))
print(metrics.classification_report(y_test, y_test_predict))

0.8299508316769536
[[ 8970   115   116    23    85     0     0     4    11     0]
 [  982  3259   438    64   259     0     0     8    25     1]
 [  685   337 10914     0   426     0     0     3    28     4]
 [   97   166    26   525    20     0     0     0     3     0]
 [  565   271   635     4  4805     4     1    15    30     3]
 [   27    26    19     0     9     9     0     0     0     0]
 [    1     1     4     0     0     0    39     0     0     0]
 [   36    37    12     0    24     0     0  1482     1     0]
 [  219   197   269     0   128     1     0    17  1608     4]
 [    3     0     6     0     7     0     0     0     0   123]]
              precision    recall  f1-score   support

          -1       0.77      0.96      0.86      9324
           0       0.74      0.65      0.69      5036
           1       0.88      0.88      0.88     12397
           2       0.85      0.63      0.72       837
           3       0.83      0.76      0.79      6333
           4       0.64  

### Decision Tree Model

In [29]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
LDA_model= LinearDiscriminantAnalysis()
LDA_model.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [30]:
## Performance Matrix on train data set
y_train_predict = LDA_model.predict(X_train)
model_score = LDA_model.score(X_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

0.47532420951164017
[[13049    85  5629   914  1598     0     6     3   437    44]
 [ 2423  1506  5734   876   435     0    18    70   352     1]
 [ 4832   177 19684    38  3518     1    13   190   646    14]
 [  396   458   419   879    43     0     0     1    15     1]
 [ 2530   374  6107   198  4544     0    12   132   768    43]
 [   39     4   130     0     8     0     5     0     0     0]
 [   11     0     9     0    58     0     1     0     9     0]
 [  812    37  1410     5    63     0     8  1100    78     2]
 [  682   119  2282    27   973     0     2   147  1640     5]
 [   12     0    15     0   243     0     0     0    64     4]]
              precision    recall  f1-score   support

          -1       0.53      0.60      0.56     21765
           0       0.55      0.13      0.21     11415
           1       0.48      0.68      0.56     29113
           2       0.30      0.40      0.34      2212
           3       0.40      0.31      0.35     14708
           4       0.00 

In [31]:
## Performance Matrix on test data set
y_test_predict = LDA_model.predict(X_test)
model_score = LDA_model.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_test_predict))
print(metrics.classification_report(y_test, y_test_predict))

0.47502353802699027
[[5499   40 2473  395  697    0    4    3  180   33]
 [1031  712 2552  365  181    0    9   26  158    2]
 [2061   78 8353   16 1523    0   12   74  275    5]
 [ 139  165  168  344   12    0    0    0    9    0]
 [1054  165 2527   70 2078    0    3   65  359   12]
 [  15    2   63    0    6    0    2    2    0    0]
 [   7    0   10    0   21    0    1    0    5    1]
 [ 371   16  654    3   24    0    1  488   35    0]
 [ 296   52  957    8  400    0    1   44  684    1]
 [   6    0    5    0   96    0    0    0   28    4]]
              precision    recall  f1-score   support

          -1       0.52      0.59      0.56      9324
           0       0.58      0.14      0.23      5036
           1       0.47      0.67      0.55     12397
           2       0.29      0.41      0.34       837
           3       0.41      0.33      0.37      6333
           4       0.00      0.00      0.00        90
           5       0.03      0.02      0.03        45
           6    

C:\Users\91982\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\91982\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\91982\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Random forest model works much better than decision tree model